import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.time.temporal.ChronoUnit;
import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class DaysRemaining {

	public static void main(String[] args) {
		System.out.println(new DaysRemaining().calculateDaysRemaining(askForTargetDate()));
	}

	public String calculateDaysRemaining(LocalDate targetDate) {
		LocalDate from = LocalDate.now();
		if(targetDate==null) return "Target Date is not valid. Note, only format yyyy-mm-dd is allowed";
		else {
			return "Days remaining " + String.valueOf(from.until(targetDate, ChronoUnit.DAYS));
		}
	}

	public static LocalDate askForTargetDate() {
		System.out.println("Enter target date");
		Scanner sc = new Scanner(System.in);
		try {
			return LocalDate.parse(sc.nextLine(), DateTimeFormatter.ISO_LOCAL_DATE);
		} catch (DateTimeParseException e) {
			return null;
		}

	}
}
