/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.*;
import static org.testng.Assert.*;

import java.io.ByteArrayInputStream;
import java.io.StringBufferInputStream;
import java.time.LocalDate;

public class DaysRemainingTest {
	
	@DataProvider(name="dates")
	public Object[][] dates(){
		return new Object[][]{
			{"2017-03-12", },
			{"2017-12-12"},
			{"2018-04-12"}
		};
	}
	
	@DataProvider(name="invaliddates")
	public Object[][] invaliddates(){
		return new Object[][]{
			{"207-03-12", },
			{"2017-17-12"},
			{"2018-04-32"}			
		};
	}
	
    @Test(dataProvider="dates")
    public void appHasAGreeting(String targetDate) {
        DaysRemaining classUnderTest = new DaysRemaining();
        System.setIn(new ByteArrayInputStream(targetDate.getBytes())); 
        assertNotNull(classUnderTest.calculateDaysRemaining(classUnderTest.askForTargetDate()), "app should have a greeting");
    }
    
    @Test(dataProvider="invaliddates")
    public void checkInvalidTargetData(String targetDate) {
        DaysRemaining classUnderTest = new DaysRemaining();
        System.setIn(new ByteArrayInputStream(targetDate.getBytes())); 
        assertEquals(classUnderTest.calculateDaysRemaining(classUnderTest.askForTargetDate()), "Target Date is not valid. Note, only format yyyy-mm-dd is allowed");
    }
    
    @Test public void checkNullTargetData() {
        DaysRemaining classUnderTest = new DaysRemaining();
        assertEquals(classUnderTest.calculateDaysRemaining(null), "Target Date is not valid. Note, only format yyyy-mm-dd is allowed");
    }
    
    @Test
    public void checkDateCalc() {
        DaysRemaining classUnderTest = new DaysRemaining();
        assertEquals(classUnderTest.calculateDaysRemaining(LocalDate.now().plusDays(35)), "Days remaining 35");
    }
}
